import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { CheckCircle2, XCircle, AlertCircle, TrendingUp, BookOpen, Home } from "lucide-react";
import { Link } from "react-router-dom";

const Feedback = () => {
  const assessmentResults = {
    totalScore: 85,
    maxScore: 100,
    timeTaken: "42 min",
    accuracy: 85,
    subject: "Mathematics",
    topic: "Algebra - Quadratic Equations",
  };

  const questionFeedback = [
    {
      id: 1,
      question: "What is the value of x in the equation 2x + 5 = 13?",
      userAnswer: "x = 4",
      correctAnswer: "x = 4",
      isCorrect: true,
      marks: 2,
      earnedMarks: 2,
      explanation: "Excellent! You correctly solved the equation by isolating x: 2x = 13 - 5, 2x = 8, x = 4.",
      steps: ["2x + 5 = 13", "2x = 13 - 5", "2x = 8", "x = 4"],
    },
    {
      id: 2,
      question: "Which of the following is NOT a renewable source of energy?",
      userAnswer: "Wind Energy",
      correctAnswer: "Coal",
      isCorrect: false,
      marks: 1,
      earnedMarks: 0,
      explanation: "Coal is a fossil fuel formed from dead plant matter over millions of years. It is non-renewable because once used, it cannot be replenished within a human lifespan. Wind energy, on the other hand, is renewable as wind is constantly generated by atmospheric conditions.",
    },
    {
      id: 3,
      question: "Explain the process of photosynthesis in plants.",
      userAnswer: "Photosynthesis is how plants make food using sunlight, water, and carbon dioxide...",
      correctAnswer: null,
      isCorrect: true,
      marks: 3,
      earnedMarks: 2.5,
      explanation: "Good understanding! Your answer covers the basic process. To improve: mention chlorophyll's role, explain the light and dark reactions more clearly, and include the chemical equation: 6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ + 6O₂",
      aiInsights: [
        "✓ Correctly identified main components (sunlight, water, CO₂)",
        "✓ Mentioned oxygen as byproduct",
        "⚠ Could elaborate on the role of chlorophyll",
        "⚠ Chemical equation would strengthen the answer",
      ],
    },
    {
      id: 4,
      question: "What is the capital of India?",
      userAnswer: "New Delhi",
      correctAnswer: "New Delhi",
      isCorrect: true,
      marks: 1,
      earnedMarks: 1,
      explanation: "Perfect! New Delhi is the capital of India.",
    },
  ];

  const recommendations = [
    {
      topic: "Renewable Energy Sources",
      priority: "High",
      description: "Review the differences between renewable and non-renewable energy sources",
      resources: 2,
    },
    {
      topic: "Photosynthesis - Chemical Equations",
      priority: "Medium",
      description: "Practice writing and balancing chemical equations for biological processes",
      resources: 3,
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-success-light/20 to-primary-light/10 p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Results Header */}
        <Card className="p-8 shadow-lg bg-gradient-to-br from-card to-success-light/30">
          <div className="text-center mb-6">
            <div className="inline-flex items-center justify-center h-20 w-20 rounded-full bg-success/20 mb-4">
              <CheckCircle2 className="h-10 w-10 text-success" />
            </div>
            <h1 className="text-4xl font-display font-bold text-foreground mb-2">
              Assessment Complete!
            </h1>
            <p className="text-muted-foreground">
              {assessmentResults.subject} - {assessmentResults.topic}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="text-center p-4 rounded-lg bg-card/50">
              <p className="text-sm text-muted-foreground mb-1">Score</p>
              <p className="text-3xl font-bold text-success">
                {assessmentResults.totalScore}/{assessmentResults.maxScore}
              </p>
            </div>
            <div className="text-center p-4 rounded-lg bg-card/50">
              <p className="text-sm text-muted-foreground mb-1">Accuracy</p>
              <p className="text-3xl font-bold text-primary">{assessmentResults.accuracy}%</p>
            </div>
            <div className="text-center p-4 rounded-lg bg-card/50">
              <p className="text-sm text-muted-foreground mb-1">Time Taken</p>
              <p className="text-3xl font-bold text-foreground">{assessmentResults.timeTaken}</p>
            </div>
            <div className="text-center p-4 rounded-lg bg-card/50">
              <p className="text-sm text-muted-foreground mb-1">Questions</p>
              <p className="text-3xl font-bold text-foreground">{questionFeedback.length}</p>
            </div>
          </div>
        </Card>

        {/* Question-by-Question Feedback */}
        <div className="space-y-4">
          <h2 className="text-2xl font-display font-semibold flex items-center gap-2">
            <BookOpen className="h-6 w-6 text-primary" />
            Detailed Feedback
          </h2>

          {questionFeedback.map((feedback) => (
            <Card
              key={feedback.id}
              className={`p-6 shadow-md border-l-4 ${
                feedback.isCorrect
                  ? "border-l-success bg-success-light/5"
                  : feedback.earnedMarks > 0
                  ? "border-l-warning bg-warning-light/5"
                  : "border-l-destructive bg-destructive/5"
              }`}
            >
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 mt-1">
                  {feedback.isCorrect ? (
                    <CheckCircle2 className="h-6 w-6 text-success" />
                  ) : feedback.earnedMarks > 0 ? (
                    <AlertCircle className="h-6 w-6 text-warning" />
                  ) : (
                    <XCircle className="h-6 w-6 text-destructive" />
                  )}
                </div>

                <div className="flex-1 space-y-4">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h3 className="font-semibold text-foreground mb-2">Q{feedback.id}. {feedback.question}</h3>
                      <div className="flex items-center gap-2 mb-3">
                        <Badge
                          className={
                            feedback.isCorrect
                              ? "bg-success/10 text-success border-success/30"
                              : feedback.earnedMarks > 0
                              ? "bg-warning/10 text-warning border-warning/30"
                              : "bg-destructive/10 text-destructive border-destructive/30"
                          }
                        >
                          {feedback.earnedMarks}/{feedback.marks} marks
                        </Badge>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-muted/30 rounded-lg">
                    <div>
                      <p className="text-sm font-medium text-muted-foreground mb-1">Your Answer:</p>
                      <p className="text-foreground">{feedback.userAnswer}</p>
                    </div>
                    {feedback.correctAnswer && (
                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-1">Correct Answer:</p>
                        <p className="text-success font-medium">{feedback.correctAnswer}</p>
                      </div>
                    )}
                  </div>

                  <div className="p-4 bg-primary-light/20 rounded-lg border border-primary/20">
                    <p className="text-sm font-semibold text-primary mb-2 flex items-center gap-2">
                      <AlertCircle className="h-4 w-4" />
                      AI Explanation
                    </p>
                    <p className="text-foreground text-sm leading-relaxed">{feedback.explanation}</p>
                  </div>

                  {feedback.steps && (
                    <div className="p-4 bg-card rounded-lg border border-border">
                      <p className="text-sm font-semibold text-foreground mb-3">Step-by-Step Solution:</p>
                      <div className="space-y-2">
                        {feedback.steps.map((step, index) => (
                          <div key={index} className="flex items-center gap-3">
                            <div className="flex-shrink-0 h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center text-xs font-medium text-primary">
                              {index + 1}
                            </div>
                            <code className="text-sm text-foreground font-mono">{step}</code>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {feedback.aiInsights && (
                    <div className="space-y-2">
                      <p className="text-sm font-semibold text-foreground">AI Analysis:</p>
                      {feedback.aiInsights.map((insight, index) => (
                        <p key={index} className="text-sm text-muted-foreground pl-4">
                          {insight}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* Recommendations */}
        <Card className="p-6 shadow-lg">
          <h2 className="text-2xl font-display font-semibold mb-4 flex items-center gap-2">
            <TrendingUp className="h-6 w-6 text-secondary" />
            Personalized Recommendations
          </h2>
          <p className="text-muted-foreground mb-6">
            Based on your performance, here are some areas to focus on:
          </p>

          <div className="space-y-4">
            {recommendations.map((rec, index) => (
              <div
                key={index}
                className="p-4 rounded-lg bg-gradient-to-r from-secondary-light/20 to-accent-light/20 border border-border"
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <h3 className="font-semibold text-foreground">{rec.topic}</h3>
                      <Badge
                        className={
                          rec.priority === "High"
                            ? "bg-destructive/10 text-destructive border-destructive/30"
                            : "bg-warning/10 text-warning border-warning/30"
                        }
                      >
                        {rec.priority} Priority
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mb-3">{rec.description}</p>
                    <Button variant="outline" size="sm" className="gap-2">
                      <BookOpen className="h-4 w-4" />
                      View {rec.resources} Resources
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Action Buttons */}
        <div className="flex items-center justify-center gap-4">
          <Link to="/student-dashboard">
            <Button variant="outline" size="lg" className="gap-2">
              <Home className="h-5 w-5" />
              Back to Dashboard
            </Button>
          </Link>
          <Link to="/assessment">
            <Button size="lg" className="gap-2">
              <BookOpen className="h-5 w-5" />
              Practice More
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Feedback;